# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57679

### Create a new chat with initial prompt
POST {{host}}:{{port}}/Chats
Content-Type: application/json

{
    "text":{{text}}
}

### Get a specific prompt in a chat
GET {{host}}:{{port}}/Chats/{{chatId}}/Prompts/{{promptId}}

### Add a prompt to existing chat
POST {{host}}:{{port}}/Chats/{{chatId}}/Prompts
Content-Type: application/json

{
    "text":{{text}}
}

###
