# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57679

# Get a specific prompt
GET {{host}}:{{port}}/Prompts/{{id}}

###

# Add a new prompt
POST {{host}}:{{port}}/Prompts
Content-Type: application/json

{
    "text": "{{text}}"
}
